# generated by datamodel-codegen:
# filename:  _envelope.v1.json

from __future__ import annotations
from typing import Annotated, Any
from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class EventEnvelopeV1(BaseModel):
    """
    Common envelope for every Redis Stream message per docs/conventions/events.md. Per-stream schemas $ref this and override `data`.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    event_id: Annotated[
        str,
        Field(
            description="ULID identifying this specific message.",
            pattern="^[0-9A-HJKMNP-TV-Z]{26}$",
        ),
    ]
    traceparent: Annotated[
        str,
        Field(
            description="W3C Trace Context traceparent header value, propagation vehicle per ADR 0015.",
            pattern="^[0-9a-f]{2}-[0-9a-f]{32}-[0-9a-f]{16}-[0-9a-f]{2}$",
        ),
    ]
    tracestate: Annotated[
        str | None,
        Field(
            description="Optional W3C tracestate value, present when the originating request had one."
        ),
    ] = None
    trace_id: Annotated[
        str,
        Field(
            description="The 32-hex trace-id segment of `traceparent`. Log-only convenience per events.md:57-59; never used for propagation.",
            pattern="^[0-9a-f]{32}$",
        ),
    ]
    occurred_at: Annotated[
        AwareDatetime, Field(description="ISO-8601 / RFC 3339 timestamp in UTC.")
    ]
    data: Annotated[
        dict[str, Any],
        Field(
            description="Per-stream payload. Stream schemas override with a concrete object shape."
        ),
    ]
