# generated by datamodel-codegen:
# filename:  events.media.indexed.v1.json

from __future__ import annotations
from typing import Annotated
from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class Data(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    media_id: Annotated[
        str,
        Field(
            description="ULID matching the `media_id` on the originating `jobs.media.index.v1` message.",
            pattern="^[0-9A-HJKMNP-TV-Z]{26}$",
        ),
    ]
    embedding_ref: Annotated[
        str,
        Field(
            description="Opaque pointer into the pgvector column populated per ADR 0009. Encoding decided by slice 6/9.",
            min_length=1,
        ),
    ]
    frames: Annotated[
        int,
        Field(
            description="Number of embedded frames — 1 for photo, N for video-keyframe per ADR 0007:48-54.",
            ge=1,
        ),
    ]
    embedder_model_id: Annotated[
        str,
        Field(
            description="Same field name as `/healthz` `embedder.model_id` (api.md:19-20) to avoid naming drift between control-plane and data-plane.",
            min_length=1,
        ),
    ]
    embedder_version: Annotated[
        str,
        Field(
            description="Same field name as `/healthz` `embedder.version`.",
            min_length=1,
        ),
    ]


class EventsMediaIndexedV1(BaseModel):
    """
    Worker → API: media indexing succeeded, embedding stored. Stream `events.media.indexed.v1` per docs/conventions/events.md:27.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    event_id: Annotated[
        str,
        Field(
            description="ULID identifying this specific message.",
            pattern="^[0-9A-HJKMNP-TV-Z]{26}$",
        ),
    ]
    traceparent: Annotated[
        str,
        Field(
            description="W3C Trace Context traceparent header value, propagation vehicle per ADR 0015.",
            pattern="^[0-9a-f]{2}-[0-9a-f]{32}-[0-9a-f]{16}-[0-9a-f]{2}$",
        ),
    ]
    tracestate: Annotated[
        str | None,
        Field(
            description="Optional W3C tracestate value, present when the originating request had one."
        ),
    ] = None
    trace_id: Annotated[
        str,
        Field(
            description="The 32-hex trace-id segment of `traceparent`. Log-only convenience per events.md:57-59; never used for propagation.",
            pattern="^[0-9a-f]{32}$",
        ),
    ]
    occurred_at: Annotated[
        AwareDatetime, Field(description="ISO-8601 / RFC 3339 timestamp in UTC.")
    ]
    data: Data
