# generated by datamodel-codegen:
# filename:  events.media.index_failed.v1.json

from __future__ import annotations
from enum import StrEnum
from typing import Annotated
from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class Code(StrEnum):
    """
    Stable, machine-readable failure code (posture per errors.md:16-19). New codes are additive per §SemVer.
    """

    unreadable_source = "unreadable_source"
    unsupported_kind = "unsupported_kind"
    embedder_error = "embedder_error"
    internal = "internal"


class Failure(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    code: Annotated[
        Code,
        Field(
            description="Stable, machine-readable failure code (posture per errors.md:16-19). New codes are additive per §SemVer."
        ),
    ]
    message: Annotated[
        str,
        Field(
            description="Human-readable failure message. Non-PII per errors.md:36-37."
        ),
    ]


class Retry(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    attempt: Annotated[
        int,
        Field(
            description="1-indexed retry counter for consumer log correlation.", ge=1
        ),
    ]
    next_at: Annotated[
        AwareDatetime | None,
        Field(
            description="RFC 3339 timestamp of the next scheduled retry, or null when the worker gives up."
        ),
    ]


class Data(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    media_id: Annotated[
        str,
        Field(
            description="ULID matching the `media_id` on the originating `jobs.media.index.v1` message.",
            pattern="^[0-9A-HJKMNP-TV-Z]{26}$",
        ),
    ]
    failure: Failure
    retry: Retry


class EventsMediaIndexFailedV1(BaseModel):
    """
    Worker → API: media indexing failed. Stream `events.media.index_failed.v1` per docs/conventions/events.md:29.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    event_id: Annotated[
        str,
        Field(
            description="ULID identifying this specific message.",
            pattern="^[0-9A-HJKMNP-TV-Z]{26}$",
        ),
    ]
    traceparent: Annotated[
        str,
        Field(
            description="W3C Trace Context traceparent header value, propagation vehicle per ADR 0015.",
            pattern="^[0-9a-f]{2}-[0-9a-f]{32}-[0-9a-f]{16}-[0-9a-f]{2}$",
        ),
    ]
    tracestate: Annotated[
        str | None,
        Field(
            description="Optional W3C tracestate value, present when the originating request had one."
        ),
    ] = None
    trace_id: Annotated[
        str,
        Field(
            description="The 32-hex trace-id segment of `traceparent`. Log-only convenience per events.md:57-59; never used for propagation.",
            pattern="^[0-9a-f]{32}$",
        ),
    ]
    occurred_at: Annotated[
        AwareDatetime, Field(description="ISO-8601 / RFC 3339 timestamp in UTC.")
    ]
    data: Data
