# generated by datamodel-codegen:
# filename:  jobs.media.index.v1.json

from __future__ import annotations
from enum import StrEnum
from typing import Annotated
from pydantic import AnyUrl, AwareDatetime, BaseModel, ConfigDict, Field


class MediaKind(StrEnum):
    """
    Media discriminator per ADR 0007.
    """

    photo = "photo"
    video = "video"


class Data(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    media_id: Annotated[
        str,
        Field(
            description="ULID primary key of the media row.",
            pattern="^[0-9A-HJKMNP-TV-Z]{26}$",
        ),
    ]
    media_kind: Annotated[
        MediaKind, Field(description="Media discriminator per ADR 0007.")
    ]
    source_uri: Annotated[
        AnyUrl,
        Field(
            description="Opaque URI the worker reads media bytes from. Object-store layout is deferred to slice 5 per ADR 0007:53-57."
        ),
    ]
    owner_account_id: Annotated[
        str,
        Field(
            description="ULID of the account that initiated indexing (RBAC principal per ADR 0005).",
            pattern="^[0-9A-HJKMNP-TV-Z]{26}$",
        ),
    ]
    event_id_ref: Annotated[
        str,
        Field(
            description="ULID of the tenant event this media belongs to (ADR 0008:44-49). Named `_ref` to disambiguate from the envelope's `event_id` (message identity).",
            pattern="^[0-9A-HJKMNP-TV-Z]{26}$",
        ),
    ]


class JobsMediaIndexV1(BaseModel):
    """
    API → worker: please index this media. Stream `jobs.media.index.v1` per docs/conventions/events.md:26.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    event_id: Annotated[
        str,
        Field(
            description="ULID identifying this specific message.",
            pattern="^[0-9A-HJKMNP-TV-Z]{26}$",
        ),
    ]
    traceparent: Annotated[
        str,
        Field(
            description="W3C Trace Context traceparent header value, propagation vehicle per ADR 0015.",
            pattern="^[0-9a-f]{2}-[0-9a-f]{32}-[0-9a-f]{16}-[0-9a-f]{2}$",
        ),
    ]
    tracestate: Annotated[
        str | None,
        Field(
            description="Optional W3C tracestate value, present when the originating request had one."
        ),
    ] = None
    trace_id: Annotated[
        str,
        Field(
            description="The 32-hex trace-id segment of `traceparent`. Log-only convenience per events.md:57-59; never used for propagation.",
            pattern="^[0-9a-f]{32}$",
        ),
    ]
    occurred_at: Annotated[
        AwareDatetime, Field(description="ISO-8601 / RFC 3339 timestamp in UTC.")
    ]
    data: Data
