/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Common envelope for every Redis Stream message per docs/conventions/events.md. Per-stream schemas $ref this and override `data`.
 */
export interface EventEnvelopeV1 {
  /**
   * ULID identifying this specific message.
   */
  event_id: string;
  /**
   * W3C Trace Context traceparent header value, propagation vehicle per ADR 0015.
   */
  traceparent: string;
  /**
   * Optional W3C tracestate value, present when the originating request had one.
   */
  tracestate?: string;
  /**
   * The 32-hex trace-id segment of `traceparent`. Log-only convenience per events.md:57-59; never used for propagation.
   */
  trace_id: string;
  /**
   * ISO-8601 / RFC 3339 timestamp in UTC.
   */
  occurred_at: string;
  /**
   * Per-stream payload. Stream schemas override with a concrete object shape.
   */
  data: {};
}
