/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Worker → API: media indexing succeeded, embedding stored. Stream `events.media.indexed.v1` per docs/conventions/events.md:27.
 */
export interface EventsMediaIndexedV1 {
  /**
   * ULID identifying this specific message.
   */
  event_id: string;
  /**
   * W3C Trace Context traceparent header value, propagation vehicle per ADR 0015.
   */
  traceparent: string;
  /**
   * Optional W3C tracestate value, present when the originating request had one.
   */
  tracestate?: string;
  /**
   * The 32-hex trace-id segment of `traceparent`. Log-only convenience per events.md:57-59; never used for propagation.
   */
  trace_id: string;
  /**
   * ISO-8601 / RFC 3339 timestamp in UTC.
   */
  occurred_at: string;
  data: {
    /**
     * ULID matching the `media_id` on the originating `jobs.media.index.v1` message.
     */
    media_id: string;
    /**
     * Opaque pointer into the pgvector column populated per ADR 0009. Encoding decided by slice 6/9.
     */
    embedding_ref: string;
    /**
     * Number of embedded frames — 1 for photo, N for video-keyframe per ADR 0007:48-54.
     */
    frames: number;
    /**
     * Same field name as `/healthz` `embedder.model_id` (api.md:19-20) to avoid naming drift between control-plane and data-plane.
     */
    embedder_model_id: string;
    /**
     * Same field name as `/healthz` `embedder.version`.
     */
    embedder_version: string;
  };
}
