/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Worker → API: media indexing failed. Stream `events.media.index_failed.v1` per docs/conventions/events.md:29.
 */
export interface EventsMediaIndexFailedV1 {
  /**
   * ULID identifying this specific message.
   */
  event_id: string;
  /**
   * W3C Trace Context traceparent header value, propagation vehicle per ADR 0015.
   */
  traceparent: string;
  /**
   * Optional W3C tracestate value, present when the originating request had one.
   */
  tracestate?: string;
  /**
   * The 32-hex trace-id segment of `traceparent`. Log-only convenience per events.md:57-59; never used for propagation.
   */
  trace_id: string;
  /**
   * ISO-8601 / RFC 3339 timestamp in UTC.
   */
  occurred_at: string;
  data: {
    /**
     * ULID matching the `media_id` on the originating `jobs.media.index.v1` message.
     */
    media_id: string;
    failure: {
      /**
       * Stable, machine-readable failure code (posture per errors.md:16-19). New codes are additive per §SemVer.
       */
      code: "unreadable_source" | "unsupported_kind" | "embedder_error" | "internal";
      /**
       * Human-readable failure message. Non-PII per errors.md:36-37.
       */
      message: string;
    };
    retry: {
      /**
       * 1-indexed retry counter for consumer log correlation.
       */
      attempt: number;
      /**
       * RFC 3339 timestamp of the next scheduled retry, or null when the worker gives up.
       */
      next_at: string | null;
    };
  };
}
