/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * API → worker: please index this media. Stream `jobs.media.index.v1` per docs/conventions/events.md:26.
 */
export interface JobsMediaIndexV1 {
  /**
   * ULID identifying this specific message.
   */
  event_id: string;
  /**
   * W3C Trace Context traceparent header value, propagation vehicle per ADR 0015.
   */
  traceparent: string;
  /**
   * Optional W3C tracestate value, present when the originating request had one.
   */
  tracestate?: string;
  /**
   * The 32-hex trace-id segment of `traceparent`. Log-only convenience per events.md:57-59; never used for propagation.
   */
  trace_id: string;
  /**
   * ISO-8601 / RFC 3339 timestamp in UTC.
   */
  occurred_at: string;
  data: {
    /**
     * ULID primary key of the media row.
     */
    media_id: string;
    /**
     * Media discriminator per ADR 0007.
     */
    media_kind: "photo" | "video";
    /**
     * Opaque URI the worker reads media bytes from. Object-store layout is deferred to slice 5 per ADR 0007:53-57.
     */
    source_uri: string;
    /**
     * ULID of the account that initiated indexing (RBAC principal per ADR 0005).
     */
    owner_account_id: string;
    /**
     * ULID of the tenant event this media belongs to (ADR 0008:44-49). Named `_ref` to disambiguate from the envelope's `event_id` (message identity).
     */
    event_id_ref: string;
  };
}
